<?php $name =  $this->getRequest()->getParam('fname').' '.$this->getRequest()->getParam('lname'); ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo 'Thank You Form' ?></h3></td>
        </tr>
    </table>
</div>
<div style="background-color:#fafafa;">
                            <p>Dear <?php echo $name; ?>,</p><br>
                            Thanks for your interest in Magento to Sugar CRM Extension. We would appreciate if you could <br />answer the following questions which would help us to get this right away to you.<br />
<br />1. What version of salesforce do you use?<br />2. Could you please tell me a few words about yourself, your role in your company and what your company does?<br />3. What is the best time and number to get in touch with you?<br /><br />We would be contacting you soon on your request.<br />Thanks<br /><br />Please click on this link to read further information about this extension.<br /><br /><a href="http://www.thylaksoft.com/Retail/MagentoSoln/MagentoEnterprise.aspx">http://www.thylaksoft.com/Retail/MagentoSoln/MagentoEnterprise.aspx</a><br /><a href="http://www.thylaksoft.com/Retail/MagentoSoln/Magento2Sugar.aspx">http://www.thylaksoft.com/Retail/MagentoSoln/Magento2Sugar.aspx</a><br /><br />
                            Regards,<br />
                            The Thylaksoft Team<br />
                            302-355-0449<br />
                            www.thylaksoft.com
</div>
<!--<div style="background-color:#fafafa;">
<p>Dear <?php //echo $name; ?>,</p><br>

Thank you for expressing interest in learning about one of Thylaksoft's solutions. A member of our team will contact you soon to discuss your needs.<br />If you need to get in touch with us immediately, please call 302-355-0449 and ask for Buyan  or Kris and we will be glad to help you rightaway.<br /><br />


Regards,<br />
The Thylaksoft Team<br />
302-355-0449<br />
www.thylaksoft.com
</div>
--><!--<div class="form-buttons" align="right"><a href="" title="Back">Back</a></div>-->
